// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 5.29.5

#include "messages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nats_study {

inline constexpr TalkMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sender_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TalkMessage::TalkMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TalkMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TalkMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TalkMessageDefaultTypeInternal() {}
  union {
    TalkMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TalkMessageDefaultTypeInternal _TalkMessage_default_instance_;

inline constexpr GreetResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : response_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        receiver_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GreetResponse::GreetResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GreetResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GreetResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GreetResponseDefaultTypeInternal() {}
  union {
    GreetResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GreetResponseDefaultTypeInternal _GreetResponse_default_instance_;

inline constexpr GreetRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sender_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        greeting_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GreetRequest::GreetRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GreetRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GreetRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GreetRequestDefaultTypeInternal() {}
  union {
    GreetRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GreetRequestDefaultTypeInternal _GreetRequest_default_instance_;
}  // namespace nats_study
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_messages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t
    TableStruct_messages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_.sender_language_),
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_.message_text_),
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_.timestamp_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetRequest, _impl_.sender_language_),
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetRequest, _impl_.greeting_text_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetResponse, _impl_.response_text_),
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetResponse, _impl_.receiver_language_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::nats_study::TalkMessage)},
        {11, -1, -1, sizeof(::nats_study::GreetRequest)},
        {21, -1, -1, sizeof(::nats_study::GreetResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::nats_study::_TalkMessage_default_instance_._instance,
    &::nats_study::_GreetRequest_default_instance_._instance,
    &::nats_study::_GreetResponse_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016messages.proto\022\nnats_study\"O\n\013TalkMess"
    "age\022\027\n\017sender_language\030\001 \001(\t\022\024\n\014message_"
    "text\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\">\n\014GreetRe"
    "quest\022\027\n\017sender_language\030\001 \001(\t\022\025\n\rgreeti"
    "ng_text\030\002 \001(\t\"A\n\rGreetResponse\022\025\n\rrespon"
    "se_text\030\001 \001(\t\022\031\n\021receiver_language\030\002 \001(\t"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    248,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};
namespace nats_study {
// ===================================================================

class TalkMessage::_Internal {
 public:
};

TalkMessage::TalkMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nats_study.TalkMessage)
}
inline PROTOBUF_NDEBUG_INLINE TalkMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nats_study::TalkMessage& from_msg)
      : sender_language_(arena, from.sender_language_),
        message_text_(arena, from.message_text_),
        _cached_size_{0} {}

TalkMessage::TalkMessage(
    ::google::protobuf::Arena* arena,
    const TalkMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TalkMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:nats_study.TalkMessage)
}
inline PROTOBUF_NDEBUG_INLINE TalkMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : sender_language_(arena),
        message_text_(arena),
        _cached_size_{0} {}

inline void TalkMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
TalkMessage::~TalkMessage() {
  // @@protoc_insertion_point(destructor:nats_study.TalkMessage)
  SharedDtor(*this);
}
inline void TalkMessage::SharedDtor(MessageLite& self) {
  TalkMessage& this_ = static_cast<TalkMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_language_.Destroy();
  this_._impl_.message_text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TalkMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TalkMessage(arena);
}
constexpr auto TalkMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TalkMessage),
                                            alignof(TalkMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TalkMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TalkMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TalkMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TalkMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TalkMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TalkMessage>(), &TalkMessage::ByteSizeLong,
            &TalkMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_._cached_size_),
        false,
    },
    &TalkMessage::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TalkMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 58, 2> TalkMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nats_study::TalkMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string sender_language = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.sender_language_)}},
    // string message_text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.message_text_)}},
    // int64 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TalkMessage, _impl_.timestamp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sender_language = 1;
    {PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.sender_language_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string message_text = 2;
    {PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.message_text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\26\17\14\0\0\0\0\0"
    "nats_study.TalkMessage"
    "sender_language"
    "message_text"
  }},
};

PROTOBUF_NOINLINE void TalkMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:nats_study.TalkMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sender_language_.ClearToEmpty();
  _impl_.message_text_.ClearToEmpty();
  _impl_.timestamp_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TalkMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TalkMessage& this_ = static_cast<const TalkMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TalkMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TalkMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nats_study.TalkMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string sender_language = 1;
          if (!this_._internal_sender_language().empty()) {
            const std::string& _s = this_._internal_sender_language();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.TalkMessage.sender_language");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string message_text = 2;
          if (!this_._internal_message_text().empty()) {
            const std::string& _s = this_._internal_message_text();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.TalkMessage.message_text");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int64 timestamp = 3;
          if (this_._internal_timestamp() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_timestamp(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nats_study.TalkMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TalkMessage::ByteSizeLong(const MessageLite& base) {
          const TalkMessage& this_ = static_cast<const TalkMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TalkMessage::ByteSizeLong() const {
          const TalkMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nats_study.TalkMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string sender_language = 1;
            if (!this_._internal_sender_language().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sender_language());
            }
            // string message_text = 2;
            if (!this_._internal_message_text().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message_text());
            }
            // int64 timestamp = 3;
            if (this_._internal_timestamp() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_timestamp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TalkMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TalkMessage*>(&to_msg);
  auto& from = static_cast<const TalkMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nats_study.TalkMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sender_language().empty()) {
    _this->_internal_set_sender_language(from._internal_sender_language());
  }
  if (!from._internal_message_text().empty()) {
    _this->_internal_set_message_text(from._internal_message_text());
  }
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TalkMessage::CopyFrom(const TalkMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nats_study.TalkMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TalkMessage::InternalSwap(TalkMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_language_, &other->_impl_.sender_language_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_text_, &other->_impl_.message_text_, arena);
        swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata TalkMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GreetRequest::_Internal {
 public:
};

GreetRequest::GreetRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nats_study.GreetRequest)
}
inline PROTOBUF_NDEBUG_INLINE GreetRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nats_study::GreetRequest& from_msg)
      : sender_language_(arena, from.sender_language_),
        greeting_text_(arena, from.greeting_text_),
        _cached_size_{0} {}

GreetRequest::GreetRequest(
    ::google::protobuf::Arena* arena,
    const GreetRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GreetRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nats_study.GreetRequest)
}
inline PROTOBUF_NDEBUG_INLINE GreetRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : sender_language_(arena),
        greeting_text_(arena),
        _cached_size_{0} {}

inline void GreetRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GreetRequest::~GreetRequest() {
  // @@protoc_insertion_point(destructor:nats_study.GreetRequest)
  SharedDtor(*this);
}
inline void GreetRequest::SharedDtor(MessageLite& self) {
  GreetRequest& this_ = static_cast<GreetRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_language_.Destroy();
  this_._impl_.greeting_text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GreetRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GreetRequest(arena);
}
constexpr auto GreetRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GreetRequest),
                                            alignof(GreetRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GreetRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GreetRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GreetRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GreetRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GreetRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GreetRequest>(), &GreetRequest::ByteSizeLong,
            &GreetRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_._cached_size_),
        false,
    },
    &GreetRequest::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GreetRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 60, 2> GreetRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nats_study::GreetRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string greeting_text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.greeting_text_)}},
    // string sender_language = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.sender_language_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sender_language = 1;
    {PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.sender_language_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string greeting_text = 2;
    {PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.greeting_text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\17\15\0\0\0\0\0"
    "nats_study.GreetRequest"
    "sender_language"
    "greeting_text"
  }},
};

PROTOBUF_NOINLINE void GreetRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nats_study.GreetRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sender_language_.ClearToEmpty();
  _impl_.greeting_text_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GreetRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GreetRequest& this_ = static_cast<const GreetRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GreetRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GreetRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nats_study.GreetRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string sender_language = 1;
          if (!this_._internal_sender_language().empty()) {
            const std::string& _s = this_._internal_sender_language();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetRequest.sender_language");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string greeting_text = 2;
          if (!this_._internal_greeting_text().empty()) {
            const std::string& _s = this_._internal_greeting_text();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetRequest.greeting_text");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nats_study.GreetRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GreetRequest::ByteSizeLong(const MessageLite& base) {
          const GreetRequest& this_ = static_cast<const GreetRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GreetRequest::ByteSizeLong() const {
          const GreetRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nats_study.GreetRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string sender_language = 1;
            if (!this_._internal_sender_language().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sender_language());
            }
            // string greeting_text = 2;
            if (!this_._internal_greeting_text().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_greeting_text());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GreetRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GreetRequest*>(&to_msg);
  auto& from = static_cast<const GreetRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nats_study.GreetRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sender_language().empty()) {
    _this->_internal_set_sender_language(from._internal_sender_language());
  }
  if (!from._internal_greeting_text().empty()) {
    _this->_internal_set_greeting_text(from._internal_greeting_text());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GreetRequest::CopyFrom(const GreetRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nats_study.GreetRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GreetRequest::InternalSwap(GreetRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_language_, &other->_impl_.sender_language_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.greeting_text_, &other->_impl_.greeting_text_, arena);
}

::google::protobuf::Metadata GreetRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GreetResponse::_Internal {
 public:
};

GreetResponse::GreetResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nats_study.GreetResponse)
}
inline PROTOBUF_NDEBUG_INLINE GreetResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nats_study::GreetResponse& from_msg)
      : response_text_(arena, from.response_text_),
        receiver_language_(arena, from.receiver_language_),
        _cached_size_{0} {}

GreetResponse::GreetResponse(
    ::google::protobuf::Arena* arena,
    const GreetResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GreetResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nats_study.GreetResponse)
}
inline PROTOBUF_NDEBUG_INLINE GreetResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : response_text_(arena),
        receiver_language_(arena),
        _cached_size_{0} {}

inline void GreetResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GreetResponse::~GreetResponse() {
  // @@protoc_insertion_point(destructor:nats_study.GreetResponse)
  SharedDtor(*this);
}
inline void GreetResponse::SharedDtor(MessageLite& self) {
  GreetResponse& this_ = static_cast<GreetResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.response_text_.Destroy();
  this_._impl_.receiver_language_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GreetResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GreetResponse(arena);
}
constexpr auto GreetResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GreetResponse),
                                            alignof(GreetResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GreetResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GreetResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GreetResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GreetResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GreetResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GreetResponse>(), &GreetResponse::ByteSizeLong,
            &GreetResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_._cached_size_),
        false,
    },
    &GreetResponse::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GreetResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 63, 2> GreetResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nats_study::GreetResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string receiver_language = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.receiver_language_)}},
    // string response_text = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.response_text_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string response_text = 1;
    {PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.response_text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string receiver_language = 2;
    {PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.receiver_language_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\15\21\0\0\0\0\0"
    "nats_study.GreetResponse"
    "response_text"
    "receiver_language"
  }},
};

PROTOBUF_NOINLINE void GreetResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nats_study.GreetResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.response_text_.ClearToEmpty();
  _impl_.receiver_language_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GreetResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GreetResponse& this_ = static_cast<const GreetResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GreetResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GreetResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nats_study.GreetResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string response_text = 1;
          if (!this_._internal_response_text().empty()) {
            const std::string& _s = this_._internal_response_text();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetResponse.response_text");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string receiver_language = 2;
          if (!this_._internal_receiver_language().empty()) {
            const std::string& _s = this_._internal_receiver_language();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetResponse.receiver_language");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nats_study.GreetResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GreetResponse::ByteSizeLong(const MessageLite& base) {
          const GreetResponse& this_ = static_cast<const GreetResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GreetResponse::ByteSizeLong() const {
          const GreetResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nats_study.GreetResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string response_text = 1;
            if (!this_._internal_response_text().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_response_text());
            }
            // string receiver_language = 2;
            if (!this_._internal_receiver_language().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_receiver_language());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GreetResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GreetResponse*>(&to_msg);
  auto& from = static_cast<const GreetResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nats_study.GreetResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_response_text().empty()) {
    _this->_internal_set_response_text(from._internal_response_text());
  }
  if (!from._internal_receiver_language().empty()) {
    _this->_internal_set_receiver_language(from._internal_receiver_language());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GreetResponse::CopyFrom(const GreetResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nats_study.GreetResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GreetResponse::InternalSwap(GreetResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.response_text_, &other->_impl_.response_text_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.receiver_language_, &other->_impl_.receiver_language_, arena);
}

::google::protobuf::Metadata GreetResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nats_study
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_messages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
