// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 6.32.1

#include "messages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nats_study {

inline constexpr TalkMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sender_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR TalkMessage::TalkMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TalkMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TalkMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TalkMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TalkMessageDefaultTypeInternal() {}
  union {
    TalkMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TalkMessageDefaultTypeInternal _TalkMessage_default_instance_;

inline constexpr GreetResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        response_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        receiver_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR GreetResponse::GreetResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GreetResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GreetResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GreetResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GreetResponseDefaultTypeInternal() {}
  union {
    GreetResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GreetResponseDefaultTypeInternal _GreetResponse_default_instance_;

inline constexpr GreetRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sender_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        greeting_text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR GreetRequest::GreetRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GreetRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GreetRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GreetRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GreetRequestDefaultTypeInternal() {}
  union {
    GreetRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GreetRequestDefaultTypeInternal _GreetRequest_default_instance_;
}  // namespace nats_study
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_messages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t
    TableStruct_messages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_.sender_language_),
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_.message_text_),
        PROTOBUF_FIELD_OFFSET(::nats_study::TalkMessage, _impl_.timestamp_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetRequest, _impl_.sender_language_),
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetRequest, _impl_.greeting_text_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetResponse, _impl_.response_text_),
        PROTOBUF_FIELD_OFFSET(::nats_study::GreetResponse, _impl_.receiver_language_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::nats_study::TalkMessage)},
        {9, sizeof(::nats_study::GreetRequest)},
        {16, sizeof(::nats_study::GreetResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::nats_study::_TalkMessage_default_instance_._instance,
    &::nats_study::_GreetRequest_default_instance_._instance,
    &::nats_study::_GreetResponse_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016messages.proto\022\nnats_study\"O\n\013TalkMess"
    "age\022\027\n\017sender_language\030\001 \001(\t\022\024\n\014message_"
    "text\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\">\n\014GreetRe"
    "quest\022\027\n\017sender_language\030\001 \001(\t\022\025\n\rgreeti"
    "ng_text\030\002 \001(\t\"A\n\rGreetResponse\022\025\n\rrespon"
    "se_text\030\001 \001(\t\022\031\n\021receiver_language\030\002 \001(\t"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    248,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};
namespace nats_study {
// ===================================================================

class TalkMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TalkMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_._has_bits_);
};

TalkMessage::TalkMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TalkMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nats_study.TalkMessage)
}
PROTOBUF_NDEBUG_INLINE TalkMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nats_study::TalkMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sender_language_(arena, from.sender_language_),
        message_text_(arena, from.message_text_) {}

TalkMessage::TalkMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TalkMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TalkMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TalkMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:nats_study.TalkMessage)
}
PROTOBUF_NDEBUG_INLINE TalkMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        sender_language_(arena),
        message_text_(arena) {}

inline void TalkMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
TalkMessage::~TalkMessage() {
  // @@protoc_insertion_point(destructor:nats_study.TalkMessage)
  SharedDtor(*this);
}
inline void TalkMessage::SharedDtor(MessageLite& self) {
  TalkMessage& this_ = static_cast<TalkMessage&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_language_.Destroy();
  this_._impl_.message_text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TalkMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TalkMessage(arena);
}
constexpr auto TalkMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TalkMessage),
                                            alignof(TalkMessage));
}
constexpr auto TalkMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TalkMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TalkMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TalkMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TalkMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TalkMessage>(), &TalkMessage::ByteSizeLong,
              &TalkMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_._cached_size_),
          false,
      },
      &TalkMessage::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TalkMessage_class_data_ =
        TalkMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TalkMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TalkMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TalkMessage_class_data_.tc_table);
  return TalkMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 58, 2>
TalkMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TalkMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nats_study::TalkMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string sender_language = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.sender_language_)}},
    // string message_text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.message_text_)}},
    // int64 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TalkMessage, _impl_.timestamp_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sender_language = 1;
    {PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.sender_language_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string message_text = 2;
    {PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.message_text_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(TalkMessage, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\26\17\14\0\0\0\0\0"
    "nats_study.TalkMessage"
    "sender_language"
    "message_text"
  }},
};
PROTOBUF_NOINLINE void TalkMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:nats_study.TalkMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.sender_language_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.message_text_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.timestamp_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TalkMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TalkMessage& this_ = static_cast<const TalkMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TalkMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TalkMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nats_study.TalkMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string sender_language = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_sender_language().empty()) {
      const ::std::string& _s = this_._internal_sender_language();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.TalkMessage.sender_language");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string message_text = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_message_text().empty()) {
      const ::std::string& _s = this_._internal_message_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.TalkMessage.message_text");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int64 timestamp = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nats_study.TalkMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TalkMessage::ByteSizeLong(const MessageLite& base) {
  const TalkMessage& this_ = static_cast<const TalkMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TalkMessage::ByteSizeLong() const {
  const TalkMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nats_study.TalkMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // string sender_language = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_sender_language().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sender_language());
      }
    }
    // string message_text = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_message_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message_text());
      }
    }
    // int64 timestamp = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TalkMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TalkMessage*>(&to_msg);
  auto& from = static_cast<const TalkMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nats_study.TalkMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_sender_language().empty()) {
        _this->_internal_set_sender_language(from._internal_sender_language());
      } else {
        if (_this->_impl_.sender_language_.IsDefault()) {
          _this->_internal_set_sender_language("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_message_text().empty()) {
        _this->_internal_set_message_text(from._internal_message_text());
      } else {
        if (_this->_impl_.message_text_.IsDefault()) {
          _this->_internal_set_message_text("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TalkMessage::CopyFrom(const TalkMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nats_study.TalkMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TalkMessage::InternalSwap(TalkMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_language_, &other->_impl_.sender_language_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_text_, &other->_impl_.message_text_, arena);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata TalkMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GreetRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GreetRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_._has_bits_);
};

GreetRequest::GreetRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GreetRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nats_study.GreetRequest)
}
PROTOBUF_NDEBUG_INLINE GreetRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nats_study::GreetRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sender_language_(arena, from.sender_language_),
        greeting_text_(arena, from.greeting_text_) {}

GreetRequest::GreetRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GreetRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GreetRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GreetRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nats_study.GreetRequest)
}
PROTOBUF_NDEBUG_INLINE GreetRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        sender_language_(arena),
        greeting_text_(arena) {}

inline void GreetRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GreetRequest::~GreetRequest() {
  // @@protoc_insertion_point(destructor:nats_study.GreetRequest)
  SharedDtor(*this);
}
inline void GreetRequest::SharedDtor(MessageLite& self) {
  GreetRequest& this_ = static_cast<GreetRequest&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_language_.Destroy();
  this_._impl_.greeting_text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GreetRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GreetRequest(arena);
}
constexpr auto GreetRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GreetRequest),
                                            alignof(GreetRequest));
}
constexpr auto GreetRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GreetRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GreetRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GreetRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GreetRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GreetRequest>(), &GreetRequest::ByteSizeLong,
              &GreetRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_._cached_size_),
          false,
      },
      &GreetRequest::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GreetRequest_class_data_ =
        GreetRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GreetRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GreetRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GreetRequest_class_data_.tc_table);
  return GreetRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 60, 2>
GreetRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GreetRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nats_study::GreetRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string greeting_text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.greeting_text_)}},
    // string sender_language = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.sender_language_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sender_language = 1;
    {PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.sender_language_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string greeting_text = 2;
    {PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.greeting_text_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\17\15\0\0\0\0\0"
    "nats_study.GreetRequest"
    "sender_language"
    "greeting_text"
  }},
};
PROTOBUF_NOINLINE void GreetRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nats_study.GreetRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.sender_language_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.greeting_text_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GreetRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GreetRequest& this_ = static_cast<const GreetRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GreetRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GreetRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nats_study.GreetRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string sender_language = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_sender_language().empty()) {
      const ::std::string& _s = this_._internal_sender_language();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetRequest.sender_language");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string greeting_text = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_greeting_text().empty()) {
      const ::std::string& _s = this_._internal_greeting_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetRequest.greeting_text");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nats_study.GreetRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GreetRequest::ByteSizeLong(const MessageLite& base) {
  const GreetRequest& this_ = static_cast<const GreetRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GreetRequest::ByteSizeLong() const {
  const GreetRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nats_study.GreetRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // string sender_language = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_sender_language().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sender_language());
      }
    }
    // string greeting_text = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_greeting_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_greeting_text());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GreetRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GreetRequest*>(&to_msg);
  auto& from = static_cast<const GreetRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nats_study.GreetRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_sender_language().empty()) {
        _this->_internal_set_sender_language(from._internal_sender_language());
      } else {
        if (_this->_impl_.sender_language_.IsDefault()) {
          _this->_internal_set_sender_language("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_greeting_text().empty()) {
        _this->_internal_set_greeting_text(from._internal_greeting_text());
      } else {
        if (_this->_impl_.greeting_text_.IsDefault()) {
          _this->_internal_set_greeting_text("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GreetRequest::CopyFrom(const GreetRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nats_study.GreetRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GreetRequest::InternalSwap(GreetRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_language_, &other->_impl_.sender_language_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.greeting_text_, &other->_impl_.greeting_text_, arena);
}

::google::protobuf::Metadata GreetRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GreetResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GreetResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_._has_bits_);
};

GreetResponse::GreetResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GreetResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nats_study.GreetResponse)
}
PROTOBUF_NDEBUG_INLINE GreetResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nats_study::GreetResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        response_text_(arena, from.response_text_),
        receiver_language_(arena, from.receiver_language_) {}

GreetResponse::GreetResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GreetResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GreetResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GreetResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nats_study.GreetResponse)
}
PROTOBUF_NDEBUG_INLINE GreetResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        response_text_(arena),
        receiver_language_(arena) {}

inline void GreetResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GreetResponse::~GreetResponse() {
  // @@protoc_insertion_point(destructor:nats_study.GreetResponse)
  SharedDtor(*this);
}
inline void GreetResponse::SharedDtor(MessageLite& self) {
  GreetResponse& this_ = static_cast<GreetResponse&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.response_text_.Destroy();
  this_._impl_.receiver_language_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GreetResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GreetResponse(arena);
}
constexpr auto GreetResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GreetResponse),
                                            alignof(GreetResponse));
}
constexpr auto GreetResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GreetResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GreetResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GreetResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GreetResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GreetResponse>(), &GreetResponse::ByteSizeLong,
              &GreetResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_._cached_size_),
          false,
      },
      &GreetResponse::kDescriptorMethods,
      &descriptor_table_messages_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GreetResponse_class_data_ =
        GreetResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GreetResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GreetResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GreetResponse_class_data_.tc_table);
  return GreetResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 63, 2>
GreetResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GreetResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nats_study::GreetResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string receiver_language = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.receiver_language_)}},
    // string response_text = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.response_text_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string response_text = 1;
    {PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.response_text_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string receiver_language = 2;
    {PROTOBUF_FIELD_OFFSET(GreetResponse, _impl_.receiver_language_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\15\21\0\0\0\0\0"
    "nats_study.GreetResponse"
    "response_text"
    "receiver_language"
  }},
};
PROTOBUF_NOINLINE void GreetResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nats_study.GreetResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.response_text_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.receiver_language_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GreetResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GreetResponse& this_ = static_cast<const GreetResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GreetResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GreetResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nats_study.GreetResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string response_text = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_response_text().empty()) {
      const ::std::string& _s = this_._internal_response_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetResponse.response_text");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string receiver_language = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._internal_receiver_language().empty()) {
      const ::std::string& _s = this_._internal_receiver_language();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nats_study.GreetResponse.receiver_language");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nats_study.GreetResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GreetResponse::ByteSizeLong(const MessageLite& base) {
  const GreetResponse& this_ = static_cast<const GreetResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GreetResponse::ByteSizeLong() const {
  const GreetResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nats_study.GreetResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // string response_text = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_response_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_response_text());
      }
    }
    // string receiver_language = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!this_._internal_receiver_language().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_receiver_language());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GreetResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GreetResponse*>(&to_msg);
  auto& from = static_cast<const GreetResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:nats_study.GreetResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_response_text().empty()) {
        _this->_internal_set_response_text(from._internal_response_text());
      } else {
        if (_this->_impl_.response_text_.IsDefault()) {
          _this->_internal_set_response_text("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (!from._internal_receiver_language().empty()) {
        _this->_internal_set_receiver_language(from._internal_receiver_language());
      } else {
        if (_this->_impl_.receiver_language_.IsDefault()) {
          _this->_internal_set_receiver_language("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GreetResponse::CopyFrom(const GreetResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nats_study.GreetResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GreetResponse::InternalSwap(GreetResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.response_text_, &other->_impl_.response_text_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.receiver_language_, &other->_impl_.receiver_language_, arena);
}

::google::protobuf::Metadata GreetResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nats_study
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_messages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
