version: '3.8'

services:
  nats-1:
    image: nats:latest
    hostname: nats-1
    command: [
      "--jetstream",
      "--cluster_name", "JSCLUSTER", 
      "--cluster", "nats://nats-1:6222",
      "--routes", "nats://nats-2:6222",
      "--server_name", "nats-1"
    ]
    ports:
      - "4222:4222"   # 客户端连接
      - "8222:8222"   # 监控页面
    volumes:
      - ./nats-1-data:/jetstream
    networks:
      - nats-cluster

  nats-2:
    image: nats:latest
    hostname: nats-2  
    command: [
      "--jetstream",
      "--cluster_name", "JSCLUSTER",
      "--cluster", "nats://nats-2:6222", 
      "--routes", "nats://nats-1:6222",
      "--server_name", "nats-2"
    ]
    ports:
      - "4223:4222"   # 客户端连接
      - "8223:8222"   # 监控页面
    volumes:
      - ./nats-2-data:/jetstream
    networks:
      - nats-cluster

networks:
  nats-cluster:
    driver: bridge
