# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\nnats_study\"O\n\x0bTalkMessage\x12\x17\n\x0fsender_language\x18\x01 \x01(\t\x12\x14\n\x0cmessage_text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\">\n\x0cGreetRequest\x12\x17\n\x0fsender_language\x18\x01 \x01(\t\x12\x15\n\rgreeting_text\x18\x02 \x01(\t\"A\n\rGreetResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12\x19\n\x11receiver_language\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TALKMESSAGE']._serialized_start=30
  _globals['_TALKMESSAGE']._serialized_end=109
  _globals['_GREETREQUEST']._serialized_start=111
  _globals['_GREETREQUEST']._serialized_end=173
  _globals['_GREETRESPONSE']._serialized_start=175
  _globals['_GREETRESPONSE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
